### PR TITLE
adding my background information

### PR DESCRIPTION
**Pull request by ToeJammm**

### CODE REVIEW

**Comment by mickidymick** [comment]
please correct the name of the markdown file per the instructions for the first task

**Comment by ToeJammm** [comment]
> please correct the name of the markdown file per the instructions for the first task

I changed it thankyou

**Comment by ToeJammm** [comment]
should I be able to see it it in students now? I currently do not.

**Comment by mickidymick** [comment]
you should be able to see it now that I have merged it

**Pull request merged**
