### PR TITLE
adding my background information

### PR DESCRIPTION
**Pull request by thanyalasagna**
hello kitty

### CODE REVIEW

**Comment by thanyalasagna** [comment]
@audrism Hi, I hope I was able to do the fork the repo properly. I went ahead and tried to do the Github Milestone but was unsure if you wanted it  under this repo as well.

It says should be for "cs340-24/test" but i only see "/news" and " /students".

Feedback would be great, thanks!

**Comment by mickidymick** [comment]
Please only add the mark down file with your info in this pr

**Comment by thanyalasagna** [comment]
is it okay now?

**Comment by mickidymick** [comment]
No, you have deleted the readme

**Comment by thanyalasagna** [comment]
Can you please elaborate? I have the introduction.md included. What is incorrect?

**Comment by mickidymick** [comment]
The PR you are pushing has changed 2 files. 1 is the thatngu1.md which is the file we need. the other file that is changed is README.md which you deleted. The only file that your pull request should be interacting with is the new introduction.md file you create. I hope that helps explain.

**Pull request closed without merging**
